// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzRooKZBBV0RyZiFyPrPWGoCBRkYMg1JI',
    appId: '1:71406549321:web:ac0141c72b009b765dc298',
    messagingSenderId: '71406549321',
    projectId: 'einvite-1857d',
    authDomain: 'einvite-1857d.firebaseapp.com',
    storageBucket: 'einvite-1857d.firebasestorage.app',
    measurementId: 'G-NE69XYB8LD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbW04sG_WF1WklMZHd0FI0DxiYYuMGxdI',
    appId: '1:71406549321:android:c97997834550b5365dc298',
    messagingSenderId: '71406549321',
    projectId: 'einvite-1857d',
    storageBucket: 'einvite-1857d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF-iFyU45bvL1ep-CUM44ev28i9lOXRCk',
    appId: '1:71406549321:ios:4bd52bc02ec7144d5dc298',
    messagingSenderId: '71406549321',
    projectId: 'einvite-1857d',
    storageBucket: 'einvite-1857d.firebasestorage.app',
    iosBundleId: 'com.vga.Envite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF-iFyU45bvL1ep-CUM44ev28i9lOXRCk',
    appId: '1:71406549321:ios:f8f3fe392ebaaef75dc298',
    messagingSenderId: '71406549321',
    projectId: 'einvite-1857d',
    storageBucket: 'einvite-1857d.firebasestorage.app',
    iosBundleId: 'com.envite.eventPlannerLight',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzRooKZBBV0RyZiFyPrPWGoCBRkYMg1JI',
    appId: '1:71406549321:web:bf4f5ac82b67c7565dc298',
    messagingSenderId: '71406549321',
    projectId: 'einvite-1857d',
    authDomain: 'einvite-1857d.firebaseapp.com',
    storageBucket: 'einvite-1857d.firebasestorage.app',
    measurementId: 'G-ENCTK06B4F',
  );
}
